### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by zvezdochiot**
add LICENSE

### CODE REVIEW

**Comment by kornelski** [comment]
The original license was public domain, which is more acceptable than WTFPL.

**Comment by zvezdochiot** [comment]
How to materially issue this public license? (URL?)

**Comment by kornelski** [comment]
http://creativecommons.org/publicdomain/mark/1.0/ ?

Also check out MozJPEG, which has IJG license and a faster implementation.

**Comment by zvezdochiot** [comment]
OK. License -> Public Domain Mark 1.0

**Comment by kornelski** [comment]
Thanks

**Pull request merged**
